### PR TITLE
Update dep

### PR DESCRIPTION
**Pull request by KostyaSha**
Allow nanliu/staging 1.0.x

### CODE REVIEW

**Comment by rtyler** [comment]
Is Nan's staging 1.x module API compatible with the older versions? If you install nanliu/staging 1.x on a machine first, and then install/use puppet-groovy,, and that all works, then this should be safe to merge

**Comment by KostyaSha** [comment]
Thanks, will check.

**Comment by KostyaSha** [comment]
Successfully Installed with staging 1.0.2 and stdlib 4.4.0. Btw, why do you need recursive symlink in module?

**Comment by rtyler** [comment]
This has been released as v1.0.3

**Pull request merged**
